safe-global/safe-docs

- source/contracts/deployment.md
typo with `initialize` in `.md`
> fix typo in deployment.md

- source/clients/android.md
- source/clients/chrome_extension.md
- source/clients/ios.md
- source/contracts/architecture.md
- source/contracts/deployment.md
- source/contracts/signatures.md
- source/contracts/transactions.md
- source/services/history.md
- source/services/index.rst
- source/services/notifications.md
- source/services/relay.md
- source/services/transactions.md
- Added install guides for clients
- Minor service updates
> Add client install guides

- source/services/notifications.md
- source/services/relay.md
- source/services/transactions.md
> Add 4Kb limit to notifications docs

- source/services/notifications.md
- source/services/relay.md
- source/services/transactions.md
- Related to https://github.com/gnosis/safe-transaction-service/issues/56
> Add setup section for relay/transaction service

- website/.env.sample
- website/siteConfig.js
Add `gaTrackingId` to siteConfig.js as a new deployment environment `GA_TACKING_ID`.
> Integrate Google Analytics

- docs/contracts_04_tx_execution.md
- docs/services_02_relay.md
- package.json
- website/core/Footer.js
- Rename DELETECALL  to DELEGATECALL (Closes #30 )
- Fix link in relay docs
- Fix link to reddit
- Adjust twitter and github links to safe related links
> Fix small issues

- docs/intro_06_audits.md
See https://github.com/gnosis/safe-contracts/pull/204
> Fix audit version number

- docs/contracts_05_relayer.md
> Fix relay link

- docs/contracts_05_relayer.md
Reminder for myself: Don't squash!
> Develop -> Master

- docs/intro_06_audits.md
- docs/intro_bug_bounty.md
- website/pages/en/index.js
- website/sidebars.json
~Please do not merge/release before the announcements~  
Links to 1.2.0 need to be checked ✅
> Add bug bounty program page

- docs/intro_06_audits.md
- docs/intro_bug_bounty.md
This is an attempt if this fixes the relative link issues
> Use absolute links for internal links

- docs/CPKtutorial1.md
- docs/CPKtutorial3.md
- docs/CPKtutorial5.md
- docs/sdks_01_overview.md
- docs/sdks_02_cpk.md
- docs/sdks_03_safe_apps.md
- package.json
- Update CPK tutorial with CPK v2.1.0 and add useful links
- Add video introduction to "Building with Safe Apps SDK & CPK" in the SDKs overview page
- Add Safe App template and video to the Safe Apps SDK overview
> Update SDKs resources

- docs/CPKtutorial1.md
- docs/CPKtutorial5.md
- docs/sdks_02_cpk.md
> Update CPK Tutorial

- docs/sdks_03_safe_apps.md
> Fix Safe app links

- docs/tutorial_tx_service_initiate_sign.md
Not sure how to set a releative link. So I mae an absolute link.
> Link was broken

- docs/contracts_08_other_evm.md
- docs/intro_06_audits.md
- docs/intro_07_bug_bounty.md
- High: 100k to 1000k
- Medium: 10k to 50k (requires approval)
- Low: 2k to 10k (requires approval)
- The tag for 1.3.0 is still missing
- The deployments for 1.3.0 in the Safe deployments repo are not final yet
> Update bug bounty relevant information

- docs/sdks_03_core.md
Update the Safe Core SDK docs with changes from last release (v0.3.1)
> Update docs for Safe Core SDK v0.3.1

- .github/scripts/prepare_production_deployment.sh
- .github/workflows/ci.yaml
Fix ref key on the production deployment script.
> Fix ref key on the production deployment script

- learn/safe-core-account-abstraction-sdk/auth-kit.md
- learn/safe-core-account-abstraction-sdk/onramp-kit.md
Update some links following a discord report
Fix an error in the auth-kit docs regarding a wrong confog prop name
> fix: Some fixes and updates

- learn/safe-core-account-abstraction-sdk/auth-kit.md
Improve docs by adding a better description and samples about how to interact with common web3 libs
> doc(auth-kit): Add how to interact with common web3 libraries

- learn/web/eip-1271.md
This updates the transaction service links from staging to productions.
> fix: adjust EIP-1271 transaction service links

- learn/safe-core/safe-core-account-abstraction-sdk/auth-kit.md
- learn/safe-core/safe-core-account-abstraction-sdk/onramp-kit.md
Reverts safe-global/safe-docs#183 because packages are not deployed and we not plan to do that until the hackaton ends
> Revert "doc(onramp-kit, auth-kit): Reflect api changes"

- README.md
- learn/safe-core/safe-core-account-abstraction-sdk/onramp-kit.md
Updating the handle for notion as it was migrated
> doc: Update notion links

- learn/safe-core/safe-core-account-abstraction-sdk/onramp-kit.md
Show how to use the Onramp Kit in a React App since the onramp kit will primarily be used with a UI context.
Include videos and screenshots to give users a clearer visualization of the Onramp Kit UX.
Related: https://github.com/5afe/safe-space/pull/8
To see how the docs look within the docs.safe.global UI, [View Documentation draft in Gitbook](https://app.gitbook.com/o/-MhyDtGxUyODu7d4sgda/s/-MhyEZtd5TVytPJtyS7v-2910905616/~/revisions/gcQy2vSvqY4UP67DtqrD/learn/safe-core/safe-core-account-abstraction-sdk/onramp-kit)
https://user-images.githubusercontent.com/9806858/228414080-59d2bc99-2323-4143-8736-24dbb175289f.mp4
> Update onramp-kit with React example

- learn/safe-core/safe-core-protocol/guards.md
- learn/safe-core/safe-core-protocol/modules-1.md
[Context](https://5afe.slack.com/archives/C04AYT81DL2/p1682583295847589)
> add modules and guard diagrams

- README.md
- examples/package.json
- examples/protocol-kit/index.ts
- examples/relay-kit/index.ts
- examples/yarn.lock
- learn/safe-core/safe-core-account-abstraction-sdk/auth-kit.md
- learn/safe-core/safe-core-account-abstraction-sdk/onramp-kit.md
- learn/safe-core/safe-core-account-abstraction-sdk/protocol-kit/README.md
- learn/safe-core/safe-core-account-abstraction-sdk/relay-kit.md
- learn/things-you-can-do-with-safe.md
Rename adapters to packs to follow latest SDK version.
Update examples to be compatible with latest SDK version
> Rename adapters to packs

- discover/safe-contract-versions.md
- learn/things-you-can-do-with-safe.md
- Merge the Safe open info Contract versions page [1] into the Safe docs and remove the existing Safe open info Contract versions page once merged.
- Add Layer 2 (L2) information
[1]: https://hackmd.io/@safe/oi/https%3A%2F%2Fhackmd.io%2F%40safe%2Fcontract-versions
> docs: Add to Things you can do with Safe and Safe contract versions

- safe-core-api/service-architecture.md
Updates the Safe Client Gateway repo url from the Rust implementation to the NodeJS implementation
> Update Safe Client Gateway repo url

- safe-core-sdk/relay-kit/gelato.md
Update docs on how to use the relay-kit as the latest implementation.
Also adds how to use the SyncFee now that it's easier
> Update relay-kit to latest implementation

- safe-core-sdk/protocol-kit/README.md
Update "Initialize Signers, Providers, and EthAdapter" section's code snippet to import dotenv/config.
The additional import provide readers a default method of including environment variables.
> chore: Update protocol-kit/README content

- .github/workflows/weekly-link-check.yml
Reverts safe-global/safe-docs#281
> Revert "Update weekly-link-check.yml"

- .github/scripts/generateSupportedNetworks.js
- components/Footer/index.tsx
- linkchecker-config.json
- pages/bug-bounty/past-paid-bounties.md
This PR:
- Updates the pattern of links we should not check (x.com, etc., as they will always fail because cannot be accessed without an X account).
- Updates the list of deprecated block explorers.
- Updates some links.
> Fix broken links

- components/Footer/index.tsx
This PR:
Standardizes the links in the footer component. Some of them are opened in the same tab but others are opened in a new one. Some wording could be improved as well.
- Refactors the Footer component
- Fixes some small wording
- Organises the links, fixes link targets and removes the unused ones
> Refactor Footer component and fix links

- .github/scripts/generateSupportedNetworks.js
- .github/styles/config/vocabularies/default/accept.txt
- pages/smart-account-supported-networks/v1.3.0.md
- pages/smart-account-supported-networks/v1.4.1.md
This PR:
- Fixes the script that generates the supported networks list
- Adds new supported networks
> Update supported networks

- .github/workflows/deploy.yml
This PR:
- Updates the `deploy.yml` script to check the `main` branch
> Deploy to staging from main branch

- components/ResourceHub/community-resources.json
Context: The tutorial show how to connect Foundry, Next.js/Wagmi/Viem to StackUp/Candide/Alchemy.
Link to Safe usage: https://youtu.be/v_V4Wqcn7vE?si=OTa-yIGystyI-LIi&t=4680
> Add a new resource

- package.json
This PR:
- Bumps the version from `v4.0.2` to `v4.1.0`
> Bump version to v4.1.0

- styles/styles.css
Table of contents is now sticky again
> Fix sticky TOC

- package.json
- theme.config.tsx
FIx head component to reactivate SEO indexing in production branches.
> fix: Fix head

- pages/api-service-architecture/safe-transaction-service.mdx
closes https://github.com/safe-global/safe-transaction-service/issues/1880
> fix: Improve Safe Transaction Service flowchart

- components/ResourceHub/Resources.tsx
Context
We want to be able to link resource types from URL in resource hub
> Add resource hub filters as query parameters

- redirects.json
This PR:
- Fixes the redirects pointing to the API pages
> fix: Update redirects

- package.json
- pages/_meta.json
- pages/advanced/_meta.json
- pages/sdk/_meta.json
This PR:
- Adds a "back" button on the top of the sidebar to go back to the "Home" page
> feat: improve visibility of resource hub and home

- pages/home/4337-guides/pimlico-sponsor-account.mdx
This PR:
- Fixes some small errors in the code snippets of the ERC-4337 guide.
- Updates the intro to give context about the complexity of the guide.
> fix: Update ERC-4337 guide

- package.json
This PR:
- Bumps the version to `4.3.0`
> chore: Bump version to 4.3.0

- pages/home/4337-guides/pimlico-sponsor-account.mdx
- theme.config.tsx
This PR:
- Adds a temporary banner with our bounties for ETHGlobal London hackathon.
- Fixes some typos and small issues in the ERC-4337 guide.
> feat: Add ETHGlobal London banner

- pages/advanced/smart-account-bug-bounty.md
Wallet related reports can be sent to separate email now.
> Update wallet reports email

- theme.config.tsx
Fix errors in setting OG attributes for all pages
> Fix open graph attributes

- pages/index.tsx
Reverts safe-global/safe-docs#420
> Revert "Redirect index to what-is-safe server-side"

- pages/glossary.md
Fixes: https://github.com/safe-global/safe-docs/issues/438
> fix: link error

- pages/home/4337-supported-networks.md
https://basescan.org/address/0xa581c4A4DB7175302464fF3C06380BC3270b4037#code
> docs: Add Base to 4337 supported networks

- .github/scripts/generateApiReference.js
- components/ApiReference/Path.tsx
- components/ApiReference/TOC.tsx
- components/ApiReference/examples/-v1-contracts--get.json
- components/ApiReference/examples/-v1-tokens--get.json
- components/ApiReference/generated-reference.mdx
- components/ApiReference/mainnet-swagger.json
This PR:
- FIxes some paddings and spaces in the script to generate the API reference .mdx file.
- Removes the extra left padding in the Path component.
- Makes the scrolls less "intrusive" by replacing "scroll" with "auto" (in the Path component and ToC)
- Edits the text in the intro.
> fix: Adjust API Reference styles

- pages/glossary.md
- pages/home/4337-guides/permissionless-detailed.mdx
- pages/home/4337-overview.mdx
- pages/home/4337-safe.mdx
This PR:
- Adds ERC-4337 terms to the Glossary
> docs: Add ERC-4337 terms to the Glossary

- package.json
- pnpm-lock.yaml
This PR:
- Updates the version of the docs to v4.5.0
- Updates the lockfile version to v9.0
> chore: Bump version to v4.5.0

- .github/workflows/link-check.yml
- linkchecker-config.json
- pages/advanced/cli-guides/recovery-safe-deployment.mdx
- pages/advanced/smart-account-modules.mdx
- pages/core-api/transaction-service-overview.mdx
- pages/glossary.md
- pages/home/4337-guides/permissionless-detailed.mdx
- pages/home/4337-guides/permissionless-quickstart.mdx
- pages/home/what-is-safe.mdx
- pages/sdk/auth-kit.mdx
- pages/sdk/onramp-kit.mdx
- pages/sdk/protocol-kit.mdx
- pages/sdk/relay-kit.mdx
- pages/sdk/relay-kit/guides/4337-safe-sdk.mdx
- Fix link check on PR github action
- Fix broken links
> Link check

- package.json
- pages/_app.tsx
- pnpm-lock.yaml
> fix: Fix google analytics

- components/ApiReference/Network.tsx
- styles/theme.ts
Fix network selector responsiveness in API reference
> fix: Minor design fix

- pages/sdk/api-kit.mdx
- pages/sdk/protocol-kit.mdx
This PR fixes:
- Fixes API Kit guide variables and signing flow
- Removes dotenv from Protocol Kit
> fix: Update API Kit guide signing flow

- .github/workflows/deploy.yml
This PR:
- Updates the `deploy.yml` script to allow temporary deployments in feature branches.
> chore: Add feature branch deployments

- pages/core-api/transaction-service-supported-networks.md
Add Scroll transaction service url.
> Add Scroll to supported networks

- pages/sdk/protocol-kit/reference/safe.md
Partially resolves: https://github.com/safe-global/safe-core-sdk/issues/851
> Add api reference for passkeys remove and swap owners

- pages/core-api/transaction-service-guides/delegates.mdx
After finishing this task https://github.com/safe-global/safe-eth-py/issues/750, the signature of the safe-eth-py Tx Service Api changed. 
It's necessary to update the examples with new method signatures.
> Update Tx Service delegate users python examples

- components/ResourceHub/community-resources.json
- components/ResourceHub/company-resources.json
https://magic.link/posts/safe-account-abstraction
> docs: add a new RH resource

- pages/sdk/relay-kit/guides/4337-safe-sdk.mdx
Resolves https://github.com/safe-global/safe-core-sdk/issues/900
> docs: Fix tabs in ERC-4337 guide

- .github/scripts/generateCodeExamples.js
This PR:
- Fixes the list of files in the `generateCodeExamples` script.
> fix: Update files list in generateCodeExamples script

- pages/advanced/cli-overview.mdx
- pages/advanced/erc-4337/guides/permissionless-detailed.mdx
- pages/advanced/erc-7579/tutorials/7579-tutorial.mdx
- pages/home/passkeys-guides/safe-sdk.mdx
- pages/home/passkeys-tutorials/safe-passkeys-tutorial.mdx
- pages/sdk/auth-kit/guides/safe-auth.mdx
- pages/sdk/protocol-kit.mdx
- pages/sdk/relay-kit/guides/4337-safe-sdk.mdx
This PR:
- Fixes some broken links
> fix: Update broken links

- components/ResourceHub/community-resources.json
More details here: https://github.com/orgs/safe-global/projects/14/views/18?sliceBy%5Bvalue%5D=DX&pane=issue&itemId=70105858
> docs: Update community resources based on the resource hub audit

- pages/sdk/_meta.json
- pages/sdk/signers.mdx
- pages/sdk/signers/_meta.json
- pages/sdk/signers/magic.mdx
- pages/sdk/signers/privy.mdx
- pages/sdk/signers/web3auth.mdx
This PR adds:
Demo app: https://github.com/5afe/safe-signers
> docs: Add signer guides

- LICENSE.md
This PR:
- Updates the License time range from `2022-2023` to `2022-2024`
> chore: Update License time range

- pages/advanced/smart-account-bug-bounty.md
Specifically, it adds the latest passkey contracts and allowance module contract releases to the bug bounty page.
> Add Latest Contracts to Bug Bounty

- .github/workflows/deploy-release.yml
- .github/workflows/deploy.yml
This PR:
- Updates pnpm from v8 to v9 in GitHub scripts
> chore: Update pnpm to v9

- .github/styles/config/vocabularies/default/accept.txt
- pages/home/glossary.md
This PR:
- Adds "Multi-signature" to the Glossary
> Add Multi-signature to the Glossary

- .github/styles/config/vocabularies/default/accept.txt
- pages/reference-sdk-starter-kit/_meta.json
- pages/reference-sdk-starter-kit/safe-client/_meta.json
- pages/reference-sdk-starter-kit/safe-client/getownerswhoapprovedtransaction.mdx
- pages/sdk/overview.mdx
- pages/sdk/starter-kit.mdx
- pages/sdk/starter-kit/guides/_meta.json
- pages/sdk/starter-kit/guides/send-transactions.mdx
- pages/sdk/starter-kit/guides/send-user-operations.mdx
This PR:
- Adds the Starter Kit section in the SDK (descriptions, overview, guides, etc.)
> docs: Add Starter Kit section

- pages/sdk/protocol-kit/reference/safe.mdx
> fix(safe-core-sdk). `init` method docs

- .github/workflows/style-check.yml
More context: https://github.com/errata-ai/vale-action/issues/128
> fix: temporary fix for the vale GH workflow

- pages/advanced/smart-account-bug-bounty.md
Solves https://github.com/safe-global/safe-docs/issues/625.
> fix: correct broken links

- pages/sdk/starter-kit/guides/send-user-operations.mdx
Also related to https://github.com/safe-global/safe-docs/commit/76cda294bae25829bfddb146e20f66087d7d4645.
> fix: incorrect package name

- components/ResourceHub/community-resources.json
- components/ResourceHub/company-resources.json
This PR:
- Reviews and updates the Resource Hub
- https://zenn.dev/kozayupapa/articles/877ca3c93fc4a9 was removed because the content is outdated (references to the Onramp Kit, EthAdapter concept, etc.)
- https://blog.logrocket.com/build-treasury-wallet-multisignature-gnosis-safe was removed because the content is outdated (old logo, package versions from Gnosis.pm, kits using `ethers` instead of `viem`, etc.)
> docs: Review and update Resource Hub

- components/ResourceHub/company-resources.json
This PR adds the React Native Passkeys tutorial to the Resource Hub as a Company resource.
> Resource hub update

- pages/advanced/smart-account-guards/smart-account-guard-tutorial.mdx
- pages/advanced/smart-account-modules/smart-account-modules-tutorial.mdx
Fixes: https://github.com/orgs/safe-global/projects/29/views/1?sliceBy%5Bvalue%5D=Engineering&pane=issue&itemId=94153679&issue=safe-global%7Cdeveloper-experience%7C332
Changes in PR:
> Create tutorial for Safe Guard

- pages/reference-smart-account/_meta.json
- pages/reference-smart-account/deployment/SafeProxy.mdx
- pages/reference-smart-account/deployment/SafeProxyFactory.mdx
- pages/reference-smart-account/deployment/SafeSingleton.mdx
- pages/reference-smart-account/deployment/_meta.json
Fixes: https://github.com/orgs/safe-global/projects/29?pane=issue&itemId=96428438&issue=safe-global%7Cdeveloper-experience%7C261 
Changes in PR:
- Add a section on deployment in references
> Create deployment reference

- pages/advanced/_meta.json
- pages/advanced/smart-account-migration.mdx
Fixes: https://github.com/orgs/safe-global/projects/29/views/1?pane=issue&itemId=96431204&issue=safe-global%7Cdeveloper-experience%7C257
Changes in PR:
- Create a page on migration
- Provide warning related to migration
- Explain available function and mention `SafeMigration` contract
- Give step-by-step tutorial for creating a migration script
- Mention source code to repository for migration script
> Add migration page

- public/llms-ctx-full.txt
- public/llms-ctx.txt
- public/llms.txt
Add publicly available text files to allow LLMs to index our docs easily, following the proposal of https://llmstxt.org/.
Add
* llms.txt: An Overview over our Docs, similar to robots.txt
* llms-ctx.txt: The content of the pages linked in llms.txt, excluding optional pages
* llms-ctx-full.txt: The content of the pages linked in llms.txt, including optional pages
This is just a first proposal.
Futher work should include optimizing the llms-ctx files and testing their efficiency, for example by adding them to the context of models and evaluate the results.
> Add llms files

- pages/advanced/smart-account-fallback-handler/smart-account-fallback-handler-tutorial.mdx
- pages/advanced/smart-account-guards/smart-account-guard-tutorial.mdx
Changes in PR:
- Add warnings in fallback handler and guard tutorials about unaudited code
> Add callouts in fallback handler and guard tutorials

- pages/sdk/protocol-kit/guides/execute-transactions.mdx
> docs: format space in execute-transactions.mdx

- pages/_meta.json
Resolves https://github.com/safe-global/developer-experience/issues/398
- Move `Safenet` tab a couple of positions to the right.
> fix(Safenet): Move tab

- components/ResourceHub/Card.tsx
- components/ResourceHub/community-resources.json
- components/ResourceHub/company-resources.json
Resolves https://github.com/safe-global/developer-experience/issues/399
- Community and company resources reviewed
- Two new company resources added
- Resources `description` property was only displayed for `Blog Post` items, but we can show it as long as there is a description.
- Resources `images` property removed from `Video` items, as they are never displayed.
> fix: Update Resource Hub

- pages/config-service-configuration/overview.mdx
- pages/core-api/safe-infrastructure-deployment.mdx
> fix: broken links between config service and api
