safe-global/safe-docs

.travis.yml
Links without trailing slash (/) need for a redirect to the link with trailing slash in AWS Cloudfront + S3 setup. By using the protocol folder directly instead of a proxy folder called current, this redirections work as expected
=> Update .travis.yml so redirection for links work

docs/intro_08_projects.md, website/pages/en/index.js, website/sidebars.json
This is to deprecate https://gist.github.com/tschubotz/03e4f6870403857d0d870a23da12680f/revisions and make people aware of other projects building on top of the Safe.
=> Add known projects integrating with the Safe.

docs/sdks_03_safe_apps.md
YouTube link should include time code because the talk starts almost 3 minutes in.
=> Changing EthCC3 talk link to contain timecode

docs/sdks_03_safe_apps.md
Update link from https://github.com/gnosis/safe-app-template (archived repository) to the new package folder of `safe-apps-sdk` (https://github.com/gnosis/safe-apps-sdk/tree/master/packages/cra-template-safe-app)
=> Update Safe cra-template link

README.md, build/projects-building-with-the-gnosis-safe.md, build/sdks/safe-apps/releasing-your-safe-app.md, contracts/gnosis-safe-on-other-evm-based-networks.md, security/bug-bounty-program.md, tutorials/batch-transactions-safe-app.md
Note: https://chat.safe.global redirects to https://discord.gg/nrQVY2566v
`curl https://chat.safe.global --head`
=> update Discord links to https://chat.safe.global

learn/safe-core-account-abstraction-sdk/onramp-kit.md
This PR document the way to enter the necessary fake and payment data to bypass the KYC process in the Stripe Widget
=> doc(onramp-kit): Add way to enter the fake data for Stripe widget

learn/safe-core-account-abstraction-sdk/onramp-kit.md
Makes a few edits to the OnrampKit docs to increase comprehension and improve UX for international users.
- Updates a link to not auto-pin to a certain locale of the Stripe blog
- Fixes grammar in a few points
=> clean up stripe onramp docs

safe-core-api/safe-transaction-service.md
Add blockchain indexing section
=> Add safe transaction indexing section

safe-core-sdk/auth-kit/guides/web3auth.md
This updates the recommended versions of the `@web3auth/*` packages to be installed with the `@safe-global/auth-kit` due to [reported bugs](https://github.com/Web3Auth/web3auth-web/issues/1589).
=> fix: update `@web3auth/*` versions

safe-core-sdk/protocol-kit/reference/migrating/v2.md
We found a small error in a code snippet that can lead developers to have trouble migrating to `protocol-kit` v2
=> fix: error in code snippet

safe-core-sdk/auth-kit/guides/safe-auth.md, safe-core-sdk/auth-kit/reference/SafeAuthPack.md
Some minor improvements to the current merged docs
=> chore: Improve auth-kit docs

safe-apps/release.md
The wallet team needs to get a first contact before they can handle a Safe App review
=> Set Google Form for first Safe App review contact

SUMMARY.md, safe-smart-account/signatures/README.md, safe-smart-account/signatures/eip-1271.md
- In [this past PR](https://github.com/safe-global/safe-docs/pull/265) the files related with Safe sigantures were removed.
- Restore the files related with Safe signatures.
=> Restore signature files

pages/api-service-architecture.md, pages/api-service-architecture/safe-transaction-service.mdx, pages/api-supported-networks.md, pages/apps-sdk-release.mdx, pages/sdk-auth-kit/guides/safe-auth.md, pages/sdk-auth-kit/reference/safe-auth-pack.md, pages/sdk-protocol-kit.md, pages/smart-account-signatures/eip-1271.md
As Safe will not support Goerli testnet anymore in Safe{Wallet} and infra starting from the 1st of Feb, we are replacing all the references in our documentation in favour of Sepolia testnet.
=> Replace Goerli with Sepolia

README.md, pages/glossary.md
This PR:
- Updates the README file content
- Fixes some broken links (not really broken) highlighted by the linkcheker.
=> Update README file

.github/workflows/deploy-release.yml, pages/api-supported-networks.md
This PR:
- Fixes the `release-deploy.yml` script
- Fixes the supported networks table
=> Fix release script

pages/api-supported-networks.md
This PR:
- Adds Base Sepolia network to the API supported networks list.
- Fixes: https://github.com/safe-global/safe-docs/issues/366
=> docs: Add Base Sepolia to API supported networks

components/ResourceHub/Resources.tsx
Fix quotes in resources hub results
=> fix: quotes in resource hub results

pages/advanced/smart-account-bug-bounty.md
- This is a result of the recent bounty submission regarding Safe Wallet.
- Slack thread here; https://5afe.slack.com/archives/C04MQSC3R7Y/p1710147174953429
=> Add reference to Safe Wallet on bug bounty page

theme.config.tsx
This PR:
- Removes the ETHGlobal London banner.
=> feat: Remove ETHGlobal London banner

pages/index.tsx
Trying to redirect from index path to `/home/what-is-safe` server-side, to fix OG metadata fetching errors.
=> Redirect index to what-is-safe server-side

pages/advanced/smart-account-bug-bounty.md
The Safe ERC-4337 module should be covered by the bug bounty program. As such, this PR adds it to the text and includes the specific Solidity file that is covered by the bounty.
=> Add Safe 4337 Module To Bug Bounty Program

.github/workflows/report-readability.yml
Readability checks not working on `.mdx` files.
It looks it's supported: https://github.com/Rebilly/lexi/blob/628628c29fa840a6497a4bcf0c3aa2012fc74d1d/src/cli/report.ts#L14-L17
This PR:
- Updates the value of the `GLOB` variable to support `.mdx` files.
Note:
- This PR is not tested.
=> chore: Add support for readability on mdx files

pages/sdk/relay-kit/guides/4337-safe-sdk.mdx, pages/sdk/relay-kit/reference/safe-4337-pack.mdx
This PR:
- After the release of the Relay Kit including the `Safe4337Pack`, this PR replaces the `alpha` version with the latest one.
=> docs: Replace RelayKit alpha version with latest

pages/sdk/protocol-kit.mdx
The example for `getPendingTransactions` fails to wrap the await in such a way to return the results.  The `getPendingTransactions` function returns a promise, so it needs to be awaited in order to then pull the results.
=> fix: Add await to getPendingTransactions call

components/ResourceHub/community-resources.json, components/ResourceHub/company-resources.json
Update the mirror blog URLs in the Resource Hub to safe.global/blog for SEO (our blog is the main asset and all the other instances are/should be canonical links). Also, regenerated the OG metadata based on the new URLs
=> fix: update blog urls from mirror to safe.global

pages/sdk/_meta.json, pages/sdk/api-kit.mdx, pages/sdk/auth-kit/guides/safe-auth.mdx, pages/sdk/overview.mdx, pages/sdk/protocol-kit.mdx, pages/sdk/protocol-kit/reference.md, pages/sdk/relay-kit.mdx
- Order the package from most used to least.
- Removes broken links pointing to Protocol Kit reference in the repository instead the docs themselves.
- Remove reference to guide in the repository to avoid moving users from docs to repo.
- Add few more links for cross docs references.
=> fix: broken links to SDK repo and remove references to guide

package.json, pages/_app.tsx, pnpm-lock.yaml
Restore react-ga4 after wrongfully removed it in https://github.com/safe-global/safe-docs/pull/490. No events are received at all anymore in GA.
=> Restore react-ga4

pages/advanced/cli-guides/recovery-safe-deployment.mdx, pages/advanced/cli-reference/common-commands.mdx
there doesn't appear to be `update_to_l2`, but `update_version_to_l2`
=> fix: wrong command name

pages/core-api/api-safe-transaction-service.mdx, pages/core-api/transaction-service-guides/_meta.json, pages/core-api/transaction-service-guides/data-decoder.mdx
Closes https://github.com/safe-global/safe-transaction-service/issues/1985
=> docs: Add Tx Service data decoder guide

styles/styles.css
This PR:
- Increases the `line-height` CSS property in the `h2` and `h3` titles. This fixes the current overlap when there are multiple lines.
=> fix: Increase line-height in titles

pages/sdk/protocol-kit/reference/safe-factory.md, pages/sdk/protocol-kit/reference/safe.md, pages/sdk/relay-kit/reference/safe-4337-pack.mdx
docs: Passkeys in the SDK references
=> docs: Passkeys in the SDK references

components/ApiReference/ApiReference.tsx, pages/core-api/transaction-service-reference.mdx
The console displayed a few thousand warnings on the API reference page about the use of useLayoutEffect inside components that are rendered and then stringified client-side. This made devtools crash and slowed down development.
=> Fix warnings in API reference

pages/home/passkeys-guides/safe-sdk.mdx, pages/sdk/protocol-kit/reference/safe-factory.md, pages/sdk/protocol-kit/reference/safe.md
Updated the `PasskeyArgType` type from:
```typescript
export type PasskeyArgType = {
rawId: ArrayBuffer // required to sign data
publicKey: ArrayBuffer // required to generate X & Y Coordinates
}
```
to:
```typescript
export type PasskeyArgType = {
rawId: string // required to sign data
coordinates: PasskeyCoordinates // required to sign data
customVerifierAddress?: string // optional
}
```
Creating and storing a passkey should be easier:
```typescript
import { PasskeyArgType, extractPasskeyData } from "@safe-global/protocol-kit";
// Generate a passkey credential using WebAuthn API
const passkeyCredential = await navigator.credentials.create({
publicKey: {
pubKeyCredParams: [
{
// ECDSA w/ SHA-256: https://datatracker.ietf.org/doc/html/rfc8152#section-8.1
alg: -7,
type: "public-key",
}, …
```
=> docs: Update Passkey type

pages/sdk/relay-kit/guides/4337-safe-sdk.mdx
In the Safe SDK guide there is a missing comma in the `paymasterOptions` object. This PR adds the missing comma. [Section](https://docs.safe.global/home/4337-guides/safe-sdk#initialize-the-safe4337pack) -> With an ERC-20 Paymaster tab
**Current**
```ts
const safe4337Pack = await Safe4337Pack.init({
// ...
paymasterOptions: {
paymasterAddress: '0x...'
paymasterTokenAddress: '0x...',
amountToApprove // Optional
}
})
```
**Updated**
```ts
const safe4337Pack = await Safe4337Pack.init({
// ...
paymasterOptions: {
paymasterAddress: '0x...',
paymasterTokenAddress: '0x...',
amountToApprove // Optional
}
})
```
=> docs: add missing comma to paymasterOptions object

examples/erc-7579/lib/permissionless.ts
This PR:
- Replaces `erc7569LaunchpadAddress` with `erc7579LaunchpadAddress` in the ERC-7579 tutorial because there was a typo in the ERC number.
=> fix: Update erc7579LaunchpadAddress

pages/core-api/transaction-service-supported-networks.md
This PR:
- Adds `X Layer` and `Linea` networks to the "Suported Networks" page in the "Safe Transaction Service" section. Now they are supported in our service and app: https://app.safe.global
=> docs: Update API supported networks

pages/sdk/protocol-kit/reference/safe.mdx
Fixes a small typo in the protocol kit SDK reference.
=> fix: typo in protocol kit reference

components/RemovedContentCallout/index.tsx, pages/sdk/onramp.mdx, pages/sdk/onramp/monerium.mdx, pages/sdk/onramp/stripe.mdx, pages/sdk/signers.mdx, redirects.json
=> docs: Update redirects for removed pages

pages/sdk/onramp/stripe.mdx, pages/sdk/overview.mdx
`stripe-server-example` GitHub repository copied from the Safe{Core} SDK repository (as it will be removed at some point) to a new location [here](https://github.com/5afe/stripe-server-example).
This PR:
- Updates the link pointing to the new Stripe server example repository.
- Removes Onramp Kit section from SDK overview.
=> docs: Update Onramp Kit removal

pages/sdk/relay-kit/guides/_meta.json, pages/sdk/relay-kit/guides/onchain-identifier.mdx
This PR:
- Moves this guide from Notion to our docs: https://safe-global.notion.site/Onchain-Identifiers-Docs-How-to-track-user-operations-dd159230b75c4994b59b05815a76c03b?pvs=74
=> docs: Add the onchain identifier guide

pages/advanced/cli-reference/common-commands.mdx, pages/advanced/smart-account-audits.md, pages/advanced/smart-account-bug-bounty.md, pages/advanced/smart-account-bug-bounty/past-paid-bounties.md, pages/advanced/smart-account-guards.mdx, pages/advanced/smart-account-overview.mdx, pages/advanced/smart-account-signatures.md, pages/core-api/api-safe-transaction-service.mdx, pages/core-api/safe-infrastructure-deployment.mdx, pages/sdk/protocol-kit/guides/signatures/messages.mdx, pages/sdk/protocol-kit/guides/signatures/transactions.mdx, pages/sdk/protocol-kit/reference/safe-factory.mdx, pages/sdk/protocol-kit/reference/safe.mdx
This PR:
- Fixes broken links pointing to `safe-eth-py` repo.
- Updates links pointing to `safe-contracts` to `safe-smart-account` repo
=> fix: Update broken links

pages/advanced/erc-4337/4337-safe.mdx, pages/advanced/erc-4337/overview.mdx, pages/home/what-is-safe.mdx, pages/sdk/relay-kit/guides/4337-safe-sdk.mdx
The Glossary page was moved to a different folder but I suspect an issue with the cache didn't highlight the broken links in the GitHub action:
- Old Glossary page (cache issue): https://docs.safe.global/glossary
- New Glossary page: https://docs.safe.global/home/glossary
This PR:
- Updates the links pointing to the Glossary with the new location.
=> fix: Update Glossary links

pages/sdk/relay-kit/guides/onchain-identifier.mdx
Hey Safe team! While preparing for a certain upcoming announcement, I stumbled across a broken link in your docs. A quick glance showed it was just missing the `h` at the beginning of `https`.
My first time contributing to the repo, so please lmk if I missed anything from the contributing guidelines.
=> chore: fix broken link

pages/core-api/transaction-service-guides/data-decoder.mdx, pages/core-api/transaction-service-guides/delegates.mdx, pages/core-api/transaction-service-guides/messages.mdx, pages/core-api/transaction-service-guides/transactions.mdx
Related with https://github.com/safe-global/safe-eth-py/pull/1286
Due to the update of the main `safe-eth-py` package, it is necessary to update the examples related to it.
=> fix: Update safe-eth-py examples package

pages/core-api/transaction-service-guides/delegates.mdx, pages/core-api/transaction-service-guides/messages.mdx, pages/core-api/transaction-service-guides/transactions.mdx, pages/reference-sdk-api-kit/proposetransaction.mdx, pages/sdk/api-kit/guides/propose-and-confirm-transactions.mdx, pages/sdk/protocol-kit.mdx, pages/sdk/protocol-kit/guides/migrate-to-v4.md, pages/sdk/relay-kit/guides/gelato-relay.mdx
This PR:
- Adds the `types-kit` renaming after the revert in https://github.com/safe-global/safe-docs/commit/93ce1caaea366b4c76f1d2ce5ba4867cb5736ffe
=> docs: Revert Types Kit revert

pages/sdk/overview.mdx, pages/sdk/relay-kit.mdx
Currently the Relay Kit description mentions ERC-4337 as the only transaction relaying mechanism (implicitly), but we are also supporting Gelato relay.
This PR:
- Adjusts the Relay Kit description.
=> docs: Update Relay Kit description

pages/sdk/protocol-kit/guides/_meta.json, pages/sdk/protocol-kit/guides/migrate-to-v5.md
Add migration guide from v4 to v5 to protocol-kit docs
=> docs: Add migration guide from v4 to v5 to protocol-kit docs

package.json
`husky install` is deprecated and should be replaced with `husky`.
This PR:
- Removes the recurrent warning after every installation of the project by updating `husky` script.
=> chore: Update husky script

pages/sdk/relay-kit/guides/gelato-relay.mdx
Currently the methods mentioned above, such as [createRelayedTransaction](https://github.com/safe-global/safe-core-sdk/blob/dc98509f15f42f04d65edcbada3bcf1f61f1154a/packages/relay-kit/src/packs/gelato/GelatoRelayPack.ts#L141C1-L150C4) and [executeRelayTransaction](https://github.com/safe-global/safe-core-sdk/blob/dc98509f15f42f04d65edcbada3bcf1f61f1154a/packages/relay-kit/src/packs/gelato/GelatoRelayPack.ts#L416C1-L424C4), have been deprecated.
This PR:
- Updates the example implementation to use the latest Safe Relay kit methods.
=> docs: Update deprecated methods

pages/sdk/overview.mdx, pages/sdk/relay-kit/guides/4337-safe-sdk.mdx
docs: Add build and Entrypoint compatibility warnings to SDK documentation
See: https://github.com/safe-global/safe-core-sdk/issues/961
=> docs: Add build and Entrypoint compatibility warnings

pages/sdk/overview.mdx
Fixes formatting error from https://github.com/safe-global/safe-docs/commit/5fbf0e3317be74f9a704903e686d467237253120#diff-1271bcc4dfa052ce7e55a97453062b7a2b41fc658c475e781d880c81b48d14e5R13 that causes the build to fail.
=> fix: formatting error causing build failure

pages/core-api/safe-contracts-deployment.mdx
Context (internal Slack link): https://5afe.slack.com/archives/C07QQSN7BK4/p1730715044170559
=> fix: show full address for the deployer

pages/core-api/safe-contracts-deployment.mdx
Adds an optional flag to inform about an env variable needed to deploy ZKsync chains.
Replaces https://github.com/safe-global/safe-docs/pull/639
=> Add zksync flag to contract deployment

pages/reference-sdk-protocol-kit/transactions/createtransaction.mdx
* Fixes default value of operationType at the `createTransaction` reference.
* Adds a sentence to describe the two possible values.
=> docs: change default value and add description to operation type at createTransaction

pages/sdk/starter-kit/guides/send-transactions.mdx
The installation command fails because the library name is incomplete.
=> Fix sdk name on send-transactions.mdx

pages/sdk/api-kit/guides/propose-and-confirm-transactions.mdx
Fix a typo in the imported package in this page https://docs.safe.global/sdk/api-kit/guides/propose-and-confirm-transactions#imports
=> docs: fix typo in `@safe-global/types-kit`

pages/reference-smart-account/setup/setup.mdx
This PR adds parameters that were missing from the Smart Account Reference page for `Safe.setup()`: `to`, `data`, `fallbackHandler`, `paymentToken`, `payment` and `paymentReceiver`.
=> fix: Add missing parameters in `Safe.setup()`

components/SupportedNetworks/Networks.tsx, pages/core-api/safe-contracts-deployment.mdx, pages/core-api/safe-infrastructure-deployment.mdx, pages/core-api/safe-installation-overview.mdx
The goal of this PR is to highlight the application form link for Safe network deployments.
Changes:
- add callouts with the form link
- add link to the PaaS with Safe
- redirect to the overview of Safe deployments from the supported networks page
=> Highlight Safe network deployments

pages/sdk/protocol-kit/guides/execute-transactions.mdx
This PR:
- Updates the Protocol Kit guide that showcases how to execute transactions. The previous one was outdated and the format was not in line with the current guides.
=> docs: Update the Protocol Kit guide to execute transactions

redirects.json
This PR:
Adds some missing redirects:
- `/sdk-protocol-kit/guides/signatures/transactions`
- `/sdk-protocol-kit/guides/signatures/messages`
- `/sdk/protocol-kit/reference`
- `/sdk/protocol-kit/reference/safe`
Updates and outdated redirect:
- `/safe-core-aa-sdk/protocol-kit/reference`
=> fix: Update Protocol Kit redirects

pages/advanced/smart-account-modules/smart-account-modules-tutorial.mdx
This PR suggests some changes in how code and concepts are introduced to reduce cognitive load of the learner and (hopefully) increase the learning experience.
=> Change code order to improve learners experience

.github/scripts/generateApiReference.ts, components/ApiReference/Property.tsx, components/ApiReference/generated-reference.mdx, components/ApiReference/mainnet-swagger.json
This PR fixes four bugs with the API reference after the transaction service upgraded it's Swagger version:
- Query parameters' types were not displayed
- Sample responses were not displayed
- Typescript examples were not displayed
- Response parameters with multiple types were not displayed correctly (e.g. `stringnull` instead of `string | null`)
=> Fix API sample responses and request parameters

pages/reference-sdk-protocol-kit/passkeys/createpasskeysigner.mdx
This PR:
- Fixes the indentation of the `return` section in the reference.
- Adds the code snippet for the `credential` parameter of the function.
=> fix: Update createPasskeySigner reference

.github/scripts/s3_upload.sh
This PR aims to speed up the deployment of the website on AWS by allowing file uploads to be performed in parallel.
=> Test uploading build output to AWS using parallel threads

components/ApiReference/Property.tsx
This PR fixes a display error where some properties descriptions include type definitions, due to how they are defined in the transaction-service repo (e.g.: [here](https://github.com/safe-global/safe-transaction-service/blob/dffb7564221bcdf6f66efce2098a8c65fb9a33dc/safe_transaction_service/history/serializers.py#L896)).
To fix it, we stop displaying the lines after the first keyword (`:param obj:`) in the description, effectively removing the extra type definitions.
Before: 
After:
=> Remove extra lines in property descriptions to avoid `:return:` expressions

.github/styles/config/vocabularies/default/accept.txt, pages/_meta.json, pages/advanced/cli-reference/common-commands.mdx, pages/advanced/passkeys/tutorials/react-native.mdx, pages/config-service-configuration/_meta.json, pages/config-service-configuration/add-or-edit-chain.mdx, pages/config-service-configuration/add-or-edit-client.mdx, pages/config-service-configuration/add-or-edit-feature.mdx, pages/config-service-configuration/add-or-edit-gas-price.mdx, pages/config-service-configuration/add-or-edit-group.mdx, pages/config-service-configuration/add-or-edit-provider.mdx, pages/config-service-configuration/add-or-edit-safe-app-feature.mdx, pages/config-service-configuration/add-or-edit-safe-app.mdx, pages/config-service-configuration/add-or-edit-social-profile.mdx, pages/config-service-configuration/add-or-edit-tag.mdx, pages/config-service-configuration/add-or-edit-wallet.mdx, pages/config-service-configuration/add-user.mdx, pages/config-service-configuration/edit-user.mdx, pages/config-service-configuration/overview.mdx, pages/core-api/_meta.json, pages/core-api/safe-infrastructure-deployment.mdx
Adds documentation for the Config service using Django admin panel. This PR documents the different parameters available for configuration.
=> feat: Config service configuration

pages/advanced/smart-account-modules.mdx
Changes in PR:
- Add link to reference in Safe Module page
- Add more content
=> Adjust content in Safe module page

pages/advanced/smart-account-modules.mdx
This PR fixes a grammatical error in the documentation heading to improve clarity. Corrected 'How _to_ Safe Modules Work' to 'How Safe Modules Work'.
=> Fix grammatical error in Safe Modules' documentation

pages/advanced/_meta.json, pages/advanced/smart-account-multi-chain-deployment.mdx
Changes in PR:
- Create a page on multichain deployment
- Mention how do deploy Safe on multiple chains at Same address: Reference Protocol Kit, Wallet UI, and help page
The page gives info on what factors address of Safe depends and avoid repeating the information already available across different articles.
=> Add a page on multi chain safe deployment

.github/scripts/generateApiReference.ts
curl sample requests in the docs wrongly have /api/api/v... instead of /api/v...
this can be seen on for example https://docs.safe.global/core-api/transaction-service-reference/mainnet#List-Multisig-Confirmations
Example:
curl -X GET https://safe-transaction-mainnet.safe.global/api/api/v1/contracts/ \
-H "Accept: application/json" \
-H "content-type: application/json" \
There's not much documententation about safe-docs and how al of these are generated, but this struck me as a likely fix.
- Fix curl api samples generation
=> fix(API): correct curl sample requests

.github/scripts/validateResources.js, components/ResourceHub/company-resources.json
Before, the resource validation was not reporting the name of the resource that produced an error. This error is now printed to console. 
Also, an erroreneous resource is tweaked. The description is shortened to under 200 characters.
=> Add name reporting to resource check and tweak one resource name

pages/reference-smart-account/deployment/SafeProxyFactory.mdx
Adds callout to deprecated function `createProxyWithCallback`.
=> add callout

pages/advanced/smart-account-overview.mdx
It fixes the wrong link on one of the pages. 
It pointed to `4337` module, but it should point to the `allowances` module.
-
=> fix: Wrong link not pointing to allowances module

components/ApiReference/Network.tsx
Fix the incorrect default value in the network selector when `sepolia` is selected
=> fix: Network selector in API examples

pages/sdk/relay-kit/reference/safe-4337-pack.mdx
Documentation covering the new `GenericFeeEstimator` [addition](https://github.com/safe-global/safe-core-sdk/pull/1238).
=> docs(relay-kit): Add comment about support for a new `GenericFeeEstimator`

pages/advanced/smart-account-bug-bounty.md
- Add a callout explaining that `bounty@safe.global` is only for smart contract related submissions, and other kinds of submissions should go to the `wallet-reports@safe.global`
- Like in #759 :shrug:
=> Add Contact for Wallet Submissions

pages/advanced/smart-account-fallback-handler/smart-account-fallback-handler-tutorial.mdx, pages/advanced/smart-account-guards/smart-account-guard-tutorial.mdx, pages/advanced/smart-account-modules/smart-account-modules-tutorial.mdx
After going through the tutorial examples, I have spotted a few inconsistencies between the three of them.
This PR addresses the differences and unifies project initialization of all three tutorials.
-
=> Unify tutorials project initialization
